name: frontend
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.7.0
  cupertino_icons: ^1.0.2
  mapbox_gl: ^0.16.0
  flutter_svg: ^1.1.6
  pointer_interceptor: ^0.9.3+3
  google_fonts: any
  dio: ^4.0.6
  flutter_bloc: any
  freezed: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  json_serializable: ^6.5.4
  build_runner: ^2.3.2


flutter:

  uses-material-design: true


  assets:
   - assets/icons/
   - assets/images/

